조서영/알고리즘스터디/0주차과제
2022-DKUS-Summer-Study/Algorithm pull request #1
Opened 2022-07-03 08:31 UTC by ChoSeoyoung

2022-07-03 08:34 UTC, developerChans requested changes
과제 폴더내에는 과제 문제만 올릴 예정입니다.
따라서 root 폴더에 
조서영/0주차/README.md
로 폴더구조를 바꾸어서 다시 pr 부탁드립니다.

2022-07-03 09:05 UTC, LMS1229 commented on 과제/0주차/조서영/README.md
> +1. 자료구조: 스택
리스트 자료형은 임의의 위치에 있는 원소에 접근이 가능합니다. 그래서 스택 구조라 볼 수 없습니다.

2022-07-03 09:08 UTC, LMS1229 commented on 과제/0주차/조서영/README.md
> +→**중복을 제거**하는 것이 큰 특징이다.
중복을 제거하기 위해, set은 어떤 방법을 썼나요??

2022-07-03 14:29 UTC, ChoSeoyoung commented on 과제/0주차/조서영/README.md
> +→**중복을 제거**하는 것이 큰 특징이다.
내부적으로 hashtable data structure로 구현되어 있다고 알고 있습니다.

2022-07-03 23:42 UTC, LMS1229 requested changes
제가 코멘트 달은 내용만 수정해주셔서 다시 PR 해주시면 되겠습니다

2022-07-03 23:42 UTC, LMS1229 commented on 과제/0주차/조서영/README.md
> +→**중복을 제거**하는 것이 큰 특징이다.
좋습니다~!

2022-07-03 23:50 UTC, developerChans commented on 과제/0주차/조서영/README.md
> +1. 자료구조: 스택
comment에서 틀린 부분이 언급된다면 수정 후 다시 pr을 해주셔야합니다.

2022-07-05 09:36 UTC, developerChans approved these changes

2022-07-06 00:37 UTC, LMS1229 commented on 조서영/0주차/README.md
> +1. list는 임의의 위치에 있는 원소에 접근이 가능하다. 따라서 스택 자료구조라고 볼 수는 없다.
그렇다면 리스트는 어떤 자료 구조가 구현되어 있는건가요?

2022-07-06 00:46 UTC, LMS1229 reviewed
코멘트 확인해주시길 바랍니다

2022-07-06 08:59 UTC, ChoSeoyoung commented on 조서영/0주차/README.md
> +1. list는 임의의 위치에 있는 원소에 접근이 가능하다. 따라서 스택 자료구조라고 볼 수는 없다.
list는 시퀀스 자료형인 것 같습니다. 그리고 list를 이용해 list의 앞뒤에서만 연산이 이루어지게 한다면 스택을 흉내낼 수도 있을 것 같습니다.

2022-07-06 10:22 UTC, developerChans commented on 조서영/0주차/README.md
> +1. list는 임의의 위치에 있는 원소에 접근이 가능하다. 따라서 스택 자료구조라고 볼 수는 없다.
좋습니다. Comment 답변이후에는 수정하셔서 업데이트 해주시면 됩니다

2022-07-08 00:11 UTC, LMS1229 approved these changes
좋습니다~!

2022-07-08 00:18 UTC, developerChans commented on 조서영/0주차/README.md
> +1. list는 임의의 위치에 있는 원소에 접근이 가능하다. 따라서 스택 자료구조라고 볼 수는 없다.
https://docs.python.org/ko/3/library/stdtypes.html#list
나중에 list 관련해서는 python document를 참고하셔도 좋을 것 같습니다

2022-07-08 00:18 UTC, merged