조서영/알고리즘스터디/2주차과제
2022-DKUS-Summer-Study/Algorithm pull request #11
Opened 2022-07-17 15:00 UTC by ChoSeoyoung

2022-07-18 09:04 UTC, LMS1229 commented on 조서영/2주차/README.md
> +- 시간복잡도: O(N^2)→너비(N)*높이(N)인 트리
해당 시간 복잡도가 나온 과정을 자세하게 알 수 있을까요?

2022-07-18 09:14 UTC, LMS1229 commented on 조서영/2주차/README.md
> +**Q. S=[-1 for i in range(n+1)]을 S=[-1]*(n+1)와 같이 바꾸었을 뿐인데 시간초과에서 통과가 되었습니다. 혹시 이유를 알 수 있을까요?**
python3로 채점하신건가요? 아니면 PyPy3로 채점하셨나요?

2022-07-18 09:16 UTC, LMS1229 commented on 조서영/2주차/README.md
> +- 시간복잡도 O(N^2)→너비(N)*높이(N)인 트리
어떻게 해서 O(N^2) 이 나오셨나요??

2022-07-18 09:18 UTC, LMS1229 commented on 조서영/2주차/README.md
> +- 시간복잡도: O(N*M)→너비(N)*깊이(M)
만들어지는 수열의 개수는 N*M 보다 훨씬 많습니다. 다시 한 번 구해주세요

2022-07-18 10:03 UTC, LMS1229 commented on 조서영/2주차/README.md
> +혹시 이 방법을 해결과 관련해서 도움이나 힌트를 받을 수 있을까요?
이 문제의 키포인트는 두 플레이어는 항상 최선의 수를 둔다는 것입니다. 
따라서 현재 차례의 플레이어 A가 빈 칸에 말을 다음의 우선 순위를 두고 둡니다.

1. A가 우승한다.
2. 무승부가 나도록 한다.
3. 상대방 B가 우승한다.

이를 토대로 이전 차례인 B 는 A와 같은 우선 순위로 플레이를 합니다. 

예를 들어 3개의 빈 칸 a,b,c 에서 a나 b에 말을 뒀을 때 상대가 최선을 다해 승리한다면 절대 승리할 수 없습니다. 하지만 c에 뒀을 때 상대가 최선을 다해도 무승부라면 c에 두는 판단이 가장 최선의 수가 되는 것이므로 현채 차례의 플레이어가 c에 둔다고 판단합니다. 

이 둘을 조합하면 먼저 시작한 플레이어 A는 현재 빈 칸에 말을 둔다면 내가 이긴 상태인지(1), 아니면 B가 내리는 최선의 결정(2)을 보고 (1) 의 경우가 있다면 우승하는 것이고 없다면 (2) 의 경우에서 B가 내린 최선 결정들 중, 자신에게 가장 유리한 결정을 고르면 됩니다. (2) 에서 B가 판단하는 결정은 위 과정을 반복하면 얻을 수 있습니다.

2022-07-18 12:03 UTC, developerChans approved these changes

2022-07-27 04:13 UTC, ChoSeoyoung commented on 조서영/2주차/README.md
> +**Q. S=[-1 for i in range(n+1)]을 S=[-1]*(n+1)와 같이 바꾸었을 뿐인데 시간초과에서 통과가 되었습니다. 혹시 이유를 알 수 있을까요?**
PyPy3로 채점했습니다!

2022-07-29 05:48 UTC, ChoSeoyoung commented on 조서영/2주차/README.md
> +- 시간복잡도: O(N^2)→너비(N)*높이(N)인 트리
위 dfs함수에서 각 재귀호출별로 dfs(n)에서 dfs(n-1)을 호출하는 횟수는 총 n번, 이는 총 n번 반복됩니다. 이때, T(0)=O(1), T(n)=O(n)T(n-1)으로 나타낼 수 있으므로, T(n)=O(n)O(n)…..O(1)=O(n)*O(n)가 됩니다. 따라서 O(n^2)가 되는 것 같습니다.

2022-07-29 05:51 UTC, ChoSeoyoung commented on 조서영/2주차/README.md
> +- 시간복잡도 O(N^2)→너비(N)*높이(N)인 트리
외판원 순회 문제와 마찬가지로 각 재귀호출별로 f(n)에서 f(n-1)을 호출하는 횟수는 총 n번, 이는 총 n번 반복되므로 위와 같이 나온 것 같습니다.

2022-07-29 06:01 UTC, ChoSeoyoung commented on 조서영/2주차/README.md
> +- 시간복잡도: O(N*M)→너비(N)*깊이(M)
O(N^M)이 나옵니다.

2022-07-30 11:08 UTC, LMS1229 commented on 조서영/2주차/README.md
> +**Q. S=[-1 for i in range(n+1)]을 S=[-1]*(n+1)와 같이 바꾸었을 뿐인데 시간초과에서 통과가 되었습니다. 혹시 이유를 알 수 있을까요?**
두 케이스 모두 이상 없습니다. 

하지만 시간적으로 봤을 땐 전자가 후자보다 많은 시간을 사용할거라 생각됩니다.

전자의 경우엔 range 인스턴스를 하나 생성하고 range인스턴스는 이터레이터 객체로서 자신이 가지고 있는 정보를 순차적으로 반환합니다. (해당 경우에선 0,1,2,3,4,... n) 이렇게 값을 반환할 때 마다 -1 이 하나씩 삽입되는 형태로 보입니다.

후자의 경우엔 (리스트의 길이)*(n+1) 의 공간을 확보하고 원래 있던 리스트에 있던 값들을 복사하는 것으로 보입니다. 

이 두 경우를 비교했을 때, 후자의 경우가 압도적으로 빠릅니다. 
(환경마다 다르지만 C에서 반복문을 이용한 배열 복사와 memcpy를 이용한 배열 복사를 비교해보시면 알 수 있습니다)

또한 2차원 배열을 만들 때, 전자의 방법과 후자의 방법을 비교하면 전자의 경우엔 각각의 행이 모두 다른 주소를 가지고 있지만 후자는 모든 행이 같은 주소를 가지게 됩니다. 즉, 전자는 계속해서 새로운 인스턴스를 만들지만 후자는 그런 과정이 전혀 없으니 이런 점도 전자의 경우가 시간을 좀 더 잡아먹는 이유가 되지 않을까 싶습니다.

2022-07-30 11:19 UTC, LMS1229 commented on 조서영/2주차/README.md
> +dfs(깊이 우선 탐색)을 이용한 완전탐색으로 문제를 풀되, 해당 가지가 유망하지 않으면 더 이상 진행하지 않는다.
이 또한 분기 한정으로 인해 N^N 가지의 모든 경우의 수를 판단하지 않습니다. 현재 행에 퀸을 둔다면 그 다음엔 몇개의 열이 후보가 되는지를 토대로 다시 한 번 구해보시길 바랍니다.

2022-07-30 11:19 UTC, LMS1229 commented on 조서영/2주차/README.md
> +또한 해당 가지가 유망한지(이전에 방문한 노드인지, 갈 수 있는 도시인지)를 판단하여 유망하지 않으면 더 이상 진행하지 않는다.
분기 한정으로 인해 O(n^n) 보다 훨씬 적은 시간을 소요합니다.

현재 남아 있는 정점이 n개라면 어느 한 점을 고르고 다음에 n-1 개의 정점에 대한 문제를 해결하면 되기에

```
T(n)=nT(n-1)+O(f(n))    //n개의 정점중 하나를 고르고 나머지 n-1 개의 정점에서 문제 해결
```

이 됩니다. 이를 통해 다시 한 번 구해보시길 바랍니다.

2022-07-30 11:20 UTC, LMS1229 requested changes
시간 복잡도를 다시 계산해주세요

2022-07-30 15:02 UTC, ChoSeoyoung commented on 조서영/2주차/README.md
> +**Q. S=[-1 for i in range(n+1)]을 S=[-1]*(n+1)와 같이 바꾸었을 뿐인데 시간초과에서 통과가 되었습니다. 혹시 이유를 알 수 있을까요?**
조금 이해가 된 것 같습니다.. 감사합니다!!

2022-07-31 09:47 UTC, LMS1229 commented
좋습니다~!

2022-07-31 09:47 UTC, merged