과제 제출입니다.
2022-DKUS-Summer-Study/Algorithm pull request #12
Opened 2022-07-17 16:39 UTC by skyriv213

남은 문제를 더 풀어보고 이전 문제들도 다시 한 번 접근해보겠습니다

2022-07-18 10:12 UTC, LMS1229 commented on 김민수/1주차/P2470.py
> +        if sum < 0:
조건문에서 tmp가 아닌 sum을 이용한 이유가 무엇인가요??

2022-07-18 10:17 UTC, LMS1229 requested changes
소스 코드와 해설을 제외한 파일은 PR 하지 말아주세요

2022-07-18 10:47 UTC, LMS1229 commented on 김민수/2주차/P15651.py
> +O(n*m)
전체 시간 복잡도 T(n) = O(n*m) 으로 나온 과정이 어떻게 되나요?

2022-07-19 01:24 UTC, developerChans requested changes
민수님 Repository에 PR 올렸습니다. idea 삭제를 위해서 pr올렸습니다.

<민수님 Repo 링크>
https://github.com/skyriv213/Algorithm/pull/3

2022-07-19 09:16 UTC, developerChans approved these changes

2022-07-26 02:31 UTC, closed without merging