과제제출
2022-DKUS-Summer-Study/Algorithm pull request #13
Opened 2022-07-18 05:11 UTC by hkh1284

2022-07-18 10:49 UTC, LMS1229 commented on 허경환/2주차/9663.py
> +#n-queen
해당 문제의 시간 복잡도는 어떻게 되나요??

2022-07-18 11:56 UTC, developerChans requested changes
파일의 맨 끝에는 공백이 있어야합니다. comment부분에 엔터를 한번 더 쳐주시면 좋습니다.
참고 링크입니다.
https://jihyehwang09.github.io/2020/04/09/no-newline-at-end-of-file/

2022-07-18 11:56 UTC, developerChans commented on 허경환/1주차/이분탐색(2470).py
> +    print(ls[0], ls[1])
Add EOF

2022-07-18 11:56 UTC, developerChans commented on 허경환/2주차/9663.py
> +print(ans)
Add EOF

2022-07-18 11:56 UTC, developerChans commented on 허경환/1주차/이분탐색(10816).py
> +        print(0, end=' ')
Add EOF

2022-07-18 12:10 UTC, hkh1284 commented on 허경환/2주차/9663.py
> +#n-queen
is_promising함수의 시간복잡도는 n이므로,
n_queen함수의 시간복잡도 T(n) = 1+2n+n * (1+2n+n * T(n+1)) = 1+2n+n*(1+2n+n*(.....(1+2n+n*1))) = O(n^n)이라고
판단하였습니다.

2022-07-19 09:15 UTC, developerChans approved these changes

2022-07-19 13:02 UTC, hkh1284 commented on 허경환/2주차/9663.py
> +#n-queen
백준에서 해당 문제가 시간초과가 뜨는데 제가 시간 복잡도를 잘못 계산한걸까요?

2022-07-20 05:11 UTC, LMS1229 commented on 허경환/2주차/9663.py
> +#n-queen
함수를 수행하다보면 is_promising 함수에 의해 다음 재귀로 넘어가는 횟수가 감소하여 *T(n) = O(n) + nT(n-1) = O(n)+n(O(n)+(n-1)T(n-2)) ...* 의 형태로 나옵니다.

이를 전개하면 *O(n)(1\*2\*3\*...\*n + 2\*3\*...\*n...)+n!* 의 모습이므로 O(n^n) 으로 볼 수 있지만 *(1\*2\*3\*...\*n + 2\*3\*...\*n...)* 은 O(n^n) 보다 작은 식으로 표현할 수 있습니다.

Hint. (1\*2\*3\*...\*n + 2\*3\*...\*n+...n+1) <= e*g(n) + 1 이고 e 는 자연 상수이며 테일러 이용하여 e를 유도 할 수 있습니다.

2022-07-21 12:50 UTC, LMS1229 approved these changes
좋습니다!

2022-07-22 03:42 UTC, merged