3주차 과제
2022-DKUS-Summer-Study/Algorithm pull request #16
Opened 2022-07-24 14:43 UTC by hkh1284

2022-07-25 10:14 UTC, LMS1229 commented on 허경환/3주차/5904.py
> +#시간복잡도 O(n)
어떻게 해서 O(n) 이 나왔나요??

2022-07-26 06:07 UTC, developerChans approved these changes

2022-08-02 05:08 UTC, LMS1229 requested changes
시간 복잡도를 계산해주세요

2022-08-10 12:25 UTC, LMS1229 commented on 허경환/5주차/1541.py
> +#시간복잡도 계산 과정
해당 알고리즘이 정당한 이유가 무엇인가요??

2022-08-10 12:25 UTC, LMS1229 commented on 허경환/5주차/1931.py
> +
일찍 끝나는 회의를 빨리 배치하는것이 해가 되는 이유가 무엇인가요??

2022-09-01 00:27 UTC, merged