장익환/알고리즘 스터디/3주차 과제 제출
2022-DKUS-Summer-Study/Algorithm pull request #17
Opened 2022-07-24 14:53 UTC by JangIkhwan

2022-07-25 10:13 UTC, LMS1229 commented on 장익환/3주차/README.md
> +        - 하지만 실제 시간 복잡도는 이보다 더 작을 것이다.
k 를 구하는 과정에서 size는 대략적으로 2배씩 늘어나니 2^k <= c*N  으로 볼 수 있습니다. 이를 통해 k 와 N사이의 대략적인 관계식이 나오니, 이를 토대로 시간 복잡도를 구해보시길 바랍니다.

2022-07-25 10:13 UTC, LMS1229 requested changes
코멘트 내용을 토대로 수정해주세요

2022-07-25 12:42 UTC, JangIkhwan commented on 장익환/3주차/README.md
> +        - 하지만 실제 시간 복잡도는 이보다 더 작을 것이다.
제가 2^k <= c * N라는 식에 대해서 궁금한 것이 있습니다. 여기서 2^k는 size의 대략적인 값으로 보면 되나요? 그리고 k를 구하는 과정을 통해서, 어떤 상수 c에 대해서 2^k <= c * N임을 만족하는 k를 구한 것이라고 이해하면 되나요?

2022-07-26 06:07 UTC, developerChans approved these changes

2022-07-26 14:34 UTC, LMS1229 commented on 장익환/3주차/README.md
> +        - 하지만 실제 시간 복잡도는 이보다 더 작을 것이다.
네. 
```c++
k++;
size = (k + 3) + 2 * temp;
```
k가 1 증가할때마다 해당 식에 의해 size값은 2배+(k+3) 만큼 증가하지만 k가 증가할수록 뒤에 있는 k+3은 무시해도 될만큼 영향이 매우 적게 됩니다. 따라서 반복문을 탈출하는 순간의 size 는 O(2^k) 라 볼 수 있습니다

2022-07-26 14:36 UTC, LMS1229 approved these changes
좋습니다!

2022-07-27 02:53 UTC, merged

2022-07-29 05:40 UTC, JangIkhwan commented on 장익환/3주차/README.md
> +        - 하지만 실제 시간 복잡도는 이보다 더 작을 것이다.
감사합니다!