김민수/3주차 분할정복 문제풀이
2022-DKUS-Summer-Study/Algorithm pull request #18
Opened 2022-07-26 02:32 UTC by skyriv213

2022-07-26 06:06 UTC, developerChans approved these changes

2022-07-26 14:39 UTC, LMS1229 commented on 김민수/3주차/P1074.py
> +-> 범위가 점차적으로 감소, 또한 해당 탐색 범위의 감소 형태는 이진탐색트리에서의 방식과 비슷하다고 생각
균형 이진 탐색 트리의 탐색은 트리의 크기가 N 일때, O(logN) 의 시간 복잡도를 가집니다. 해당 문제의 입력 크기를 통해, 다시 생각해보시길 바랍니다

2022-07-27 02:51 UTC, LMS1229 requested changes
코멘트 내용을 통해 수정바랍니다

2022-07-31 10:03 UTC, LMS1229 commented on 김민수/4주차/P11053.py
> +시간복잡도는 o(n^2)이라고 생각한다.
memo[i] 를 j 를 이용해 표현한다면 어떻게 표현할 수 있나요?

2022-07-31 10:05 UTC, LMS1229 commented on 김민수/4주차/P1932.py
> +아래에서 위로 접근하는 방식의 바텀업(상향식) 방법을 사용하며 접근을 하였다.
triangle[i][j] 는 무엇을 의미하나요?

2022-08-07 16:47 UTC, skyriv213 commented on 김민수/4주차/P1932.py
> +아래에서 위로 접근하는 방식의 바텀업(상향식) 방법을 사용하며 접근을 하였다.
해당 문제를 코드 작성 및 채점을 완료한 줄 알고 올렸습니다. 이문제는 추후에 다시 작성 및 완료를 하여 제출하겠습니다

2022-08-07 17:00 UTC, skyriv213 commented on 김민수/4주차/P11053.py
> +시간복잡도는 o(n^2)이라고 생각한다.
어떻게 표현한다는 것이 정확히 어떤 의미인지 설명해주실수 있나요? 
두 번째 반복문 안에 조건문이 성립이 된 후의 memo[i]= memo[j]+1이라 생각할 수 있을것같습니다. 작성한 코드를 보면 만약 num[i]가 num[j]보다 크다면, 그리고 memo[i]가 memo[j]보다 작다면 이전의 수를 가져오도록 작성이 되어있습니다. 추후에는 반복문이 지나고 나서는 무조건 +1을 하기에 
만약 원하는 값을 구한다면 memo[i]는 memo[j]+1 이라 볼 것같습니다.

2022-08-07 17:08 UTC, skyriv213 commented on 김민수/3주차/P1074.py
> +-> 범위가 점차적으로 감소, 또한 해당 탐색 범위의 감소 형태는 이진탐색트리에서의 방식과 비슷하다고 생각
해당 문제의 경우 균형 이진트리의 시간복잡도를 생각했던 이유는 균형 이진트리처럼 점차적으로 범위가 좁혀질 것이라 생각하여 이리 답을 냈었습니다. 다만 생각이 날 때마다 시간복잡도를 다시 한 번 생각해 보았지만 정확한 답이 떠오르지는 않았습니다. 혹시 괜찮으시다면 이 과정을 도출하는데 필요한 정보나 힌트를 주실수 있나요?

2022-08-10 12:07 UTC, LMS1229 commented on 김민수/3주차/P1074.py
> +-> 범위가 점차적으로 감소, 또한 해당 탐색 범위의 감소 형태는 이진탐색트리에서의 방식과 비슷하다고 생각
이 문제의 N에 대해서 행렬의 행과 열의 크기는 2^N 입니다. 줄어드는 범위의 초기값은 N에서 절반씩 줄어드는 것이 아닌, 2^N에서 절반씩 줄어든다고 볼 수 있습니다.

2022-08-10 12:17 UTC, LMS1229 commented on 김민수/4주차/P11053.py
> +시간복잡도는 o(n^2)이라고 생각한다.
memo[i] 에 최종적으로 저장될 값을 j 를 이용해 수식으로 어떻게 표현할 수 있을지에 대한 질문이였습니다.
혹시 설명해주신 내용을 수식으로 적어주실 수 있을까요?

2022-08-10 12:24 UTC, LMS1229 commented on 김민수/5주차/P1931.py
> +한 회의실에서 가능한 최대 회의 수를 구하는 문제이므로 저장이 된 tmp가 i보다 작은 경우 회의의 수를 늘려주면 된다.
일찍 끝나는 회의를 최대한 빨리 하도록 배치하는 것이 가장 많은 회의를 배치하는 방법이 되는 이유가 무엇인가요??

2022-08-11 08:25 UTC, developerChans approved these changes

2022-08-11 15:02 UTC, skyriv213 commented on 김민수/5주차/P1931.py
> +한 회의실에서 가능한 최대 회의 수를 구하는 문제이므로 저장이 된 tmp가 i보다 작은 경우 회의의 수를 늘려주면 된다.
문제의 경우 처음에는 문제의 시작시간과 끝나는 시간이 랜덤으로 주어지게 됩니다.  문제의 경우 짧게 끝나는 회의와 빠르게 시작되는 회의의 경우 두 가지를 찾았어야 합니다. 처음 문제를 풀면서 정렬의 기준을 회의의 시작 시간을 1순위로, 그 다음 끝나는 시간을 2순위로 잡았었습니다. 다만 이런 경우에는 문제의 채점과정 중에서 오답이라는 답이 도출이 되었고 그 다음 회의의 끝나는 시간을 1순위로 잡게 되었습니다. 회의의 끝나는 시간이 1순위로 잡고, 끝나는 시간을 위주로 정렬이 된 상태에서 시작시간 정렬을 통해 문제에서 원하는 빠르게 끝나고 빠르게 시작하는 순서로 정렬할 수 있었습니다.

2022-08-11 15:05 UTC, skyriv213 commented on 김민수/4주차/P11053.py
> +시간복잡도는 o(n^2)이라고 생각한다.
아 memo[i] = memo[j]+1 이라고 생각했습니다

2022-08-14 06:34 UTC, LMS1229 commented on 김민수/5주차/P1931.py
> +한 회의실에서 가능한 최대 회의 수를 구하는 문제이므로 저장이 된 tmp가 i보다 작은 경우 회의의 수를 늘려주면 된다.
소스 코드의 내용이 아닌 코드에 쓰인 알고리즘의 정당성에 관한 질문입니다. 코드에 쓰인 알고리즘이 정당한 이유가 무엇인가요??

2022-08-15 07:57 UTC, skyriv213 commented on 김민수/5주차/P1931.py
> +한 회의실에서 가능한 최대 회의 수를 구하는 문제이므로 저장이 된 tmp가 i보다 작은 경우 회의의 수를 늘려주면 된다.
알고리즘의 정당성을 증명하기 위해 제가 작성했던 정렬의 반대 되는 상황을 생각해보았습니다.
먼저 정렬을 시키는 이유는 각 경우에 맞는 최적의 시간을 찾기 위해서였습니다.

처음 정렬에서 끝나는 시간을 1순위로 두고 진행을 하였습니다.

만약 끝나는 시간이 아닌 다른 경우로 진행을 하면 어떻게 되는지 살펴보았습니다.
문제의 경우 하나의 방에서 진행할 수 있는 최대 회의의 횟수입니다.
1. 정렬의 1순위가 시작시간인 경우
    1.1 시작시간을 기준으로만 정렬
        - 만약 시작 시간으로 정렬을 하여 문제를 풀어나간 경우 시작시간이 제일 긴 회의인 경우 
        회의의 시간이 길어진만큼 그 안에 존재하는 회의들을 해당 회의실에서 진행을 못하게됩니다.
        만약 정렬을 한 경우 시작시간은 0이지만 끝나는 시간이 12인 경우 해당 for문 반복을 통해 이 경우를 
        더하게 되는 경우 0-12 사이의 시간의 회의는 회의실을 쓰지 못하게 됩니다.
        그러므로 해당의 경우는 제외
        
    1.2 시작시간으로 정렬 후 끝나는 시간으로 추가 정렬
        - 시작시간을 기준으로 정렬한 뒤 끝나는 시간을 기준으로 한번 더 추가 정렬을 해준다면 
        같은 시작 시간을 기준으로 좀 더 회의시간이 짧은 경우를 선택해서 진행 할 수는 있지만
        만약 시작시간은 더 느리지만 더 빨리 끝나는 회의가 있다면 이 경우에는 빨리 끝나는 회의를 택하는게 맞지만
        해당 for문에서는 해당 방법을 사용 시 시작시간이 빠른 경우를 택하기에 이번 경우도 제외입니다.
        이번 경우를 통해 우리는 정렬의 기준을 회의의 끝나는 시간을 기준으로 해야한다는 것을 알 수 있었습니다.
        
2. 정렬의 기준이 끝나는 시간인 경우
    2.1 끝나는 시간으로만 정렬
        -  끝나는 시간으로만 정렬을 진행했을 경우 해당 경우는 시작 시간은 해당 정렬에 영향을 끼치지 못합니다.
        그래서 끝나는 시간을 기준으로 정렬을 한다면 시간차이를 고려하지 못하게 됩니다.
        이번 경우를 통해 이 경우는 제외가 됩니다.
    
    2.2 끝나는 시간 - 시작시간 정렬인 경우 : 정렬의 방법으로 선택이 된 이유
        -  이런 방식으로 정렬 시 끝나는 시간을 우선적으로 정렬 추가로 시작 시간을 기준으로 정렬
        이 경우에는 시작시간도 빠르고 끝나는 시간과 시작 시간의 차가 작은것부터 정렬이 가능하기에 알고리즘에
        선택이 되었습니다

2022-08-16 09:39 UTC, LMS1229 commented on 김민수/5주차/P1931.py
> +한 회의실에서 가능한 최대 회의 수를 구하는 문제이므로 저장이 된 tmp가 i보다 작은 경우 회의의 수를 늘려주면 된다.
정렬은 문제에 쓰이는 알고리즘을 빠르게 수행하기 위한 전처리입니다. (우선으로 배치할 회의를 빨리 찾기 위한 방법)
정렬 방법의 경우로 문제에 쓰인 알고리즘의 정당성 증명에 쓰이기엔 무리가 있어 보입니다. 그 이유는 다음과 같습니다. 

```
정렬의 기준은 마지막 회의가 끝난 기준으로 우선적으로 배치할 회의의 기준이 됩니다. 

위와 같은 배치할 기준외의 방법이 옳지 않음을 통해 증명하기 위해선 다른 기준들에 대해서 최적해를 보장하는 지를 모두 증명해야 합니다. 

이 기준은 매우 많아, 단순히 3가지 케이스론 증명하기엔 무리 입니다. 

1가지 예시로 다음과 같습니다. 

1. 가장 덜 겹치는 회의를 우선으로 배치

```

따라서 해당 증명으론 알고리즘의 정당성을 보이긴 어려울 것 같습니다. 다시 증명해주세요

2022-09-01 00:28 UTC, merged