장익환_알고리즘 스터디_0주차 과제
2022-DKUS-Summer-Study/Algorithm pull request #3
Opened 2022-07-03 16:24 UTC by JangIkhwan

2022-07-03 23:30 UTC, LMS1229 commented on 장익환/0주차/장익환_과제0.md
> + std::set는 key라는 원소의 집합으로 구성된 것이다. 중복되는 key 값은 존재하지 않는다는 특징이 있다. std::set을 사용하려면 <set> 헤더파일을 추가해야 한다.
set은 어떤 자료 구조인가요??

2022-07-03 23:53 UTC, developerChans approved these changes

2022-07-04 00:09 UTC, JangIkhwan commented on 장익환/0주차/장익환_과제0.md
> + std::set는 key라는 원소의 집합으로 구성된 것이다. 중복되는 key 값은 존재하지 않는다는 특징이 있다. std::set을 사용하려면 <set> 헤더파일을 추가해야 한다.
연관컨테이너인 Set도 이진 탐색트리로 구현되어 있습니다. 수학에서 집합과 같은 역할을 한다고 이해했습니다.

2022-07-04 01:53 UTC, LMS1229 commented on 장익환/0주차/장익환_과제0.md
> + std::set는 key라는 원소의 집합으로 구성된 것이다. 중복되는 key 값은 존재하지 않는다는 특징이 있다. std::set을 사용하려면 <set> 헤더파일을 추가해야 한다.
좋아요~!

2022-07-04 01:54 UTC, LMS1229 requested changes
코멘트 단 부분만 수정해주시고 다시 PR 해주세요

2022-07-04 08:08 UTC, merged