임찬솔/알고리즘과제/0주차
2022-DKUS-Summer-Study/Algorithm pull request #4
Opened 2022-07-04 17:15 UTC by Elandland

2022-07-06 00:42 UTC, developerChans commented on 임찬솔/0주차/과제
> +
test

2022-07-06 00:43 UTC, LMS1229 requested changes
코멘트 내용을 토대로 수정후 PR 해주시길 바랍니다

2022-07-06 00:43 UTC, LMS1229 commented on 임찬솔/0주차/과제
> +따라서 구조 자체가 느리다. 대신 최댓값,최솟값 반환 메소드, 통계메소드를 지원함
어떤 구조여서 느린가요?

2022-07-06 00:43 UTC, LMS1229 commented on 임찬솔/0주차/과제
> +가장 빠른 자료구조 but 순서보장,정렬 x
HashMap이 가장 빠른 이유는 무엇이죠?

2022-07-06 00:43 UTC, LMS1229 commented on 임찬솔/0주차/과제
> +LinkedHashMap
HashMap과는 어떤 차이가 있나요?

2022-07-06 00:49 UTC, developerChans requested changes

2022-07-06 00:49 UTC, developerChans commented on 임찬솔/0주차/과제
> +따라서 data를 삽입,삭제할 경우에는 빠르게 처리할 수 있음 (O(1))
정말 O(1)일까요?
data를 특정 위치에 삽입 삭제를 하게 된다면, 최대 얼마만큼의 시간 복잡도를 필요로 할까요?

2022-07-10 16:32 UTC, Elandland commented on 임찬솔/0주차/과제
> +따라서 data를 삽입,삭제할 경우에는 빠르게 처리할 수 있음 (O(1))
어느 위치인지 못찾으므로 최대한 시간이 걸릴경우 O(n)이 걸릴 것으로 예상됩니다.

2022-07-10 16:34 UTC, Elandland commented on 임찬솔/0주차/과제
> +중복을 자동으로 제거해준다는 점에서 용도를 다양하게 사용 가능
배열 구조입니다.

2022-07-10 16:37 UTC, Elandland commented on 임찬솔/0주차/과제
> +따라서 구조 자체가 느리다. 대신 최댓값,최솟값 반환 메소드, 통계메소드를 지원함
이름에서 알수 있다시피 이진탐색트리 구조입니다. 이진 탐색 트리의 특징을 그대로 가지고 왔기에 정렬,탐색에는 사용하기 편하고 삽입 삭제등이 오래걸립니다.

2022-07-10 17:01 UTC, Elandland commented on 임찬솔/0주차/과제
> +HashMap과 Set 인터페이스를 상속하여 빠른 연산이 가능한 자료형
hashset이 set에 포함되는 범위라 뭘 묻는지 정확히 모르겠습니다.
hashset에 추가된 기능을 말하시는 거라면 map인터페이스를 통해 키와 값을 받아 빠르게 연산을 처리하는 점이 다릅니다.

2022-07-11 00:16 UTC, Elandland commented on 임찬솔/0주차/과제
> +LinkedHashMap
hashmap은 데이터를 순서 상관없이 저장하고 LinkedHashMap은 data를 순서대로 저장합니다

2022-07-11 00:16 UTC, Elandland commented on 임찬솔/0주차/과제
> +따라서 구조 자체가 느리다. 대신 최댓값,최솟값 반환 메소드, 통계메소드를 지원함
이름에서 알수 있다시피 이진탐색트리 구조입니다. 이진 탐색 트리의 특징을 그대로 가지고 왔기에 정렬,탐색에는 사용하기 편하고 삽입 삭제등이 오래걸립니다.

2022-07-11 00:16 UTC, Elandland commented on 임찬솔/0주차/과제
> +따라서 data를 삽입,삭제할 경우에는 빠르게 처리할 수 있음 (O(1))
어느 위치인지 못찾으므로 최대한 시간이 걸릴경우 O(n)이 걸릴 것으로 예상됩니다.

2022-07-11 00:16 UTC, Elandland commented on 임찬솔/0주차/과제
> +가장 빠른 자료구조 but 순서보장,정렬 x
hash구조를 이용하여 키와 밸류값을 통해 정보를 저장하므로 tree구조를 사용한 treemap과 같은것보다 빠른 연산이 가능합니다.

2022-07-11 00:44 UTC, LMS1229 approved these changes

2022-07-11 00:45 UTC, merged