조서영/알고리즘스터디/1주차과제
2022-DKUS-Summer-Study/Algorithm pull request #6
Opened 2022-07-08 03:45 UTC by ChoSeoyoung

2022-07-08 04:07 UTC, developerChans requested changes
파일의 맨 끝에는 공백이 있어야합니다. 많은 사람들이 잘 모르는 사소한 git 실수입니다
참고 링크입니다.
https://jihyehwang09.github.io/2020/04/09/no-newline-at-end-of-file/

2022-07-08 04:07 UTC, developerChans commented on 조서영/1주차/2805.py
> +print(high)
Add EOF

2022-07-08 04:07 UTC, developerChans commented on 조서영/1주차/1920.py
> +    print(binary_search(A, i))
Add EOF

2022-07-08 04:07 UTC, developerChans commented on 조서영/1주차/13397.py
> +print(high)
Add EOF

2022-07-08 04:07 UTC, developerChans commented on 조서영/1주차/10816.py
> +print(' '.join(result))
Add EOF

2022-07-08 04:16 UTC, LMS1229 commented on 조서영/1주차/10816.py
> +for i in B:
dictionary 를 사용하지 않고 이진 탐색으로 풀어주세요

2022-07-08 04:19 UTC, LMS1229 commented on 조서영/1주차/13397.py
> +while low<high:
해당 반복문의 불변식은 어떻게 되나요?

2022-07-08 04:20 UTC, developerChans approved these changes

2022-07-08 04:23 UTC, LMS1229 commented on 조서영/1주차/README.md
> +while low<high:
해당 반복분에서 불변식은 어떻게 되나요?

2022-07-08 04:24 UTC, LMS1229 commented on 조서영/1주차/README.md
> +- 결정 문제: N개의 수로 이루어진 1차원 배열을 구간을 나눴을 때, 해당 구간의 최댓값이 기준값(mid)보다 작은 구간의 개수가 M개 보다 작은가를 판별하는 것
결정 문제의 형태로 바꾸었을 때 기준값에 대해서 단조 감소 함수의 형태인가요? 아니면 단조 증가 함수의 형태인가요?

2022-07-08 04:25 UTC, LMS1229 commented on 조서영/1주차/README.md
> +
two pointer가 아닌 이분 탐색으로 다시 풀어주시기 바랍니다

2022-07-08 04:27 UTC, LMS1229 commented on 조서영/1주차/README.md
> +dictionary를 이용하여, 해당 카드를 입력받을 때마다 해당 key값의 value를 증가시켰다. 만약 해당 카드가 dictionary에 존재하지 않으면 0개의 카드가 존재하는 것으로, dictionary에 존재한다면 해당카드번호를 key값으로 하여 value값을 출력한다.
hash table 를 이용하지 않고 이진 탐색으로 풀어주시길 바랍니다

2022-07-08 04:28 UTC, LMS1229 requested changes
이분 탐색으로 풀지 않은 문제들은 이분 탐색을 이용해 다시 풀어주시기 바랍니다.

2022-07-08 14:03 UTC, ChoSeoyoung commented on 조서영/1주차/README.md
> +- 결정 문제: N개의 수로 이루어진 1차원 배열을 구간을 나눴을 때, 해당 구간의 최댓값이 기준값(mid)보다 작은 구간의 개수가 M개 보다 작은가를 판별하는 것
단조 감소의 형태입니다.

2022-07-08 14:33 UTC, LMS1229 commented on 조서영/1주차/README.md
> +- 결정 문제: N개의 수로 이루어진 1차원 배열을 구간을 나눴을 때, 해당 구간의 최댓값이 기준값(mid)보다 작은 구간의 개수가 M개 보다 작은가를 판별하는 것
왜 단조 감소 함수의 형태인가요??

2022-07-08 14:56 UTC, ChoSeoyoung commented on 조서영/1주차/README.md
> +- 결정 문제: N개의 수로 이루어진 1차원 배열을 구간을 나눴을 때, 해당 구간의 최댓값이 기준값(mid)보다 작은 구간의 개수가 M개 보다 작은가를 판별하는 것
기준값(mid)값이 커지게 된다면 구간의 최댓값이 기준값을 넘기 않도록 구간을 나눴을 때 구간의 개수는 일정하거나 감소하게 됩니다. 그 이유는 구간의 개수나 변하지 않거나 구간의 범위를 더 넓게 나눔으로써 총 구간의 개수가 감소하기 때문입니다.

2022-07-08 15:05 UTC, ChoSeoyoung commented on 조서영/1주차/README.md
> +while low<high:
low<high, 그리고 solve(low)>=solve(mid)>=solve(high)입니다.

2022-07-08 23:43 UTC, LMS1229 commented on 조서영/1주차/README.md
> +while low<high:
해당 불변식이 반복문 진입과 수행, 종료시에도 유지가 되는지 설명해주실 수 있나요?

2022-07-08 23:45 UTC, LMS1229 commented on 조서영/1주차/README.md
> +- 결정 문제: N개의 수로 이루어진 1차원 배열을 구간을 나눴을 때, 해당 구간의 최댓값이 기준값(mid)보다 작은 구간의 개수가 M개 보다 작은가를 판별하는 것
네 좋습니다!

2022-07-09 06:02 UTC, ChoSeoyoung commented on 조서영/1주차/README.md
> +while low<high:
반복문의 진입시 low<high이 성립합니다. 입력값에서 배열에 들어있는 수는 1보다 크거나 같다는 조건이 있기 때문입니다. 반복문의 수행시에도 low=mid+1, high=mid의 형태로 값이 변하기 때문에 이는 성립합니다. 반복문의 종료시 low==high가 됨으로써 반복문이 종료됩니다.

2022-07-09 08:37 UTC, LMS1229 commented on 조서영/1주차/README.md
> +while low<high:
네 좋습니다! 하지만 해당 식에서 low와 high 사이의 불변식이 low<high 라면 반복문 종료시엔 불변식이 만족되지 않으므로 low+1<high 가 되어야 맞습니다.

2022-07-09 08:42 UTC, LMS1229 commented on 조서영/1주차/2470_2.py
> +    b_tmp=(idx+1)+search(S[idx+1:b_tmp+1:], -S[(a_tmp)])
해당 코드의 같은 경우, S[idx+1:b_tmp+1:] 구문에서 S의 일부분을 복사하게 되므로 전체 시간 복잡도는 O(N^2) 이 됩니다. S 를 복사하지 않는 방법으로 접근하셔야 합니다.

2022-07-09 10:25 UTC, ChoSeoyoung commented on 조서영/1주차/2470_2.py
> +    b_tmp=(idx+1)+search(S[idx+1:b_tmp+1:], -S[(a_tmp)])
미처 생각하지 못했던 부분이네요.. 감사합니다!

2022-07-09 11:16 UTC, LMS1229 approved these changes
좋아요~!

2022-07-09 11:17 UTC, merged