두 번째 문제풀이 입니다.
2022-DKUS-Summer-Study/Algorithm pull request #8
Opened 2022-07-11 05:44 UTC by skyriv213

2022-07-11 06:54 UTC, LMS1229 commented on 김민수/1주차/P10816.py
> +이진 탐색으로는 일단 접근의 방법을 찾지 못함
이진 탐색으로 푸시길 바랍니다. 
하나 힌트를 드리자면 [0,1,1,1,3,4,6] 에서 1의 개수와 1의 위치 사이의 관계를 관찰 해보시길 바랍니다

2022-07-11 06:55 UTC, LMS1229 commented on 김민수/1주차/P2470.py
> +문제의 경우 투 포인터로 접근하라 하였다. 따라서 처음에 정렬이 된 리스트를 입력 받고 진행한다
이진 탐색으로 풀어주시길 바랍니다

2022-07-11 06:55 UTC, LMS1229 requested changes
소스 코드와 해설을 제외한 파일은 PR 하지 말아주세요

2022-07-11 08:17 UTC, developerChans requested changes
가장 밖에있는 README.md 파일 은 어디에 들어가야할까요?

파일의 맨 끝에는 공백이 있어야합니다. 따라서 116번째 줄에서 엔터를 한번 더 쳐주시면 좋습니다.
참고 링크입니다.
https://jihyehwang09.github.io/2020/04/09/no-newline-at-end-of-file/

2022-07-11 08:17 UTC, developerChans commented on 김민수/1주차/P10816.py
> +    print( count[i+10000000], end = " ")
공백 EOF

2022-07-11 08:17 UTC, developerChans commented on 김민수/1주차/P2470.py
> +print(liquid1,liquid2)
공백 EOF

2022-07-12 09:57 UTC, skyriv213 commented
수정해서 지속적으로 올리겠습니다

2022-07-12 11:13 UTC, developerChans approved these changes

2022-07-13 05:10 UTC, LMS1229 approved these changes
수고하셨습니다~!

2022-07-13 12:36 UTC, merged